<?php
use Illuminate\Database\Seeder;
class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $today = new DateTime('now');
        DB::table('users')->insert(array(
            array(
                'id'                 => 1,
                'name'               => 'Attila Lakatos',
                'email'              => 'attila.lakatos@gmail.com',
                'password'           => bcrypt('aaaaaa'),
                'role'               => 'veterinarian',
                'country'            => 'Slovakia',
                'city'               => 'Zlatna na Ostrove',
                'street'             => 'Horksy rad 490',
                'zipCode'            => '94612',
                'bankAccountNumber'  => 'EG12QA3658',
                'wage'               => '1200',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 2,
                'name'               => 'Matthew Willis',
                'email'              => 'matthewwillis@gmail.com',
                'password'           => bcrypt('matthewwillis'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 120',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK',
                'wage'               => '1190',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 3,
                'name'               => 'Sam Mason',
                'email'              => 'sammason@gmail.com',
                'password'           => bcrypt('sammason'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 121',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK121',
                'wage'               => '1180',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 4,
                'name'               => 'Daniel Williams',
                'email'              => 'danielwilliams@gmail.com',
                'password'           => bcrypt('danielwilliams'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 122',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK122',
                'wage'               => '1170',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 5,
                'name'               => 'Dominic Barrera',
                'email'              => 'dominicbarrera@gmail.com',
                'password'           => bcrypt('dominicbarrera'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 122',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK122',
                'wage'               => '1170',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 6,
                'name'               => 'Jason Gomez',
                'email'              => 'jasongomez@gmail.com',
                'password'           => bcrypt('jasongomez'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 123',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK123',
                'wage'               => '1160',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 7,
                'name'               => 'Anders Hughes',
                'email'              => 'andershughes@gmail.com',
                'password'           => bcrypt('andershughes'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 124',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK124',
                'wage'               => '1150',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 8,
                'name'               => 'Lee Harris',
                'email'              => 'leeharis@gmail.com',
                'password'           => bcrypt('leeharis'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 125',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK125',
                'wage'               => '1140',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 9,
                'name'               => 'Steff Walsh',
                'email'              => 'steffwalsh@gmail.com',
                'password'           => bcrypt('steffwalsh'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 126',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK126',
                'wage'               => '1130',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 10,
                'name'               => 'Harley Rose',
                'email'              => 'harleyrose@gmail.com',
                'password'           => bcrypt('harleyrose'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 127',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK127',
                'wage'               => '1130',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 11,
                'name'               => 'Caden Fraser',
                'email'              => 'cadenfraser@gmail.com',
                'password'           => bcrypt('cadenfraser'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 128',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK128',
                'wage'               => '1120',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 12,
                'name'               => 'Vic Moore',
                'email'              => 'vicmoore@gmail.com',
                'password'           => bcrypt('vicmoore'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 129',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK129',
                'wage'               => '1110',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 13,
                'name'               => 'Frankie Nicholson',
                'email'              => 'frankienicholson@gmail.com',
                'password'           => bcrypt('frankienicholson'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 130',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK130',
                'wage'               => '1100',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 14,
                'name'               => 'Cameron Marshall',
                'email'              => 'cameronmarshall@gmail.com',
                'password'           => bcrypt('cameronmarshall'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 131',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK131',
                'wage'               => '1090',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 15,
                'name'               => 'Jess Lowe',
                'email'              => 'jesslowe@gmail.com',
                'password'           => bcrypt('jesslowe'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 132',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK132',
                'wage'               => '1080',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 16,
                'name'               => 'Jaime Sweet',
                'email'              => 'jaimesweet@gmail.com',
                'password'           => bcrypt('jaimesweet'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Tynwald hill 133',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK133',
                'wage'               => '1070',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 17,
                'name'               => 'Kris Francis',
                'email'              => 'krisfrancis@gmail.com',
                'password'           => bcrypt('krisfrancis'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Stanley road 134',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK134',
                'wage'               => '1060',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 18,
                'name'               => 'Bennie Ball',
                'email'              => 'bennieball@gmail.com',
                'password'           => bcrypt('bennieball'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Hampstead road 115',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK135',
                'wage'               => '1050',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 19,
                'name'               => 'Reed Walker',
                'email'              => 'reedwalker@gmail.com',
                'password'           => bcrypt('reedwalker'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Huntly road 136',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK136',
                'wage'               => '1040',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 20,
                'name'               => 'Terry Adams',
                'email'              => 'terryadams@gmail.com',
                'password'           => bcrypt('terryadams'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Malden road 405',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK137',
                'wage'               => '1030',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 21,
                'name'               => 'Charlie Fletcher',
                'email'              => 'charliefletcher@gmail.com',
                'password'           => bcrypt('charliefletcher'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Liverpool',
                'street'             => 'Malden road 420',
                'zipCode'            => '61543',
                'bankAccountNumber'  => 'ABCDEFGHIJK420',
                'wage'               => '1180',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 22,
                'name'               => 'Jackie Valenzuela',
                'email'              => 'jackievalenzuela@gmail.com',
                'password'           => bcrypt('jackievalenzuela'),
                'role'               => 'veterinarian',
                'country'            => 'England',
                'city'               => 'Birmingham',
                'street'             => 'Bacon road 1',
                'zipCode'            => '35005',
                'bankAccountNumber'  => 'QWERTYUI1',
                'wage'               => '1400',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 23,
                'name'               => 'Terry Slater',
                'email'              => 'terryslater@gmail.com',
                'password'           => bcrypt('terryslater'),
                'role'               => 'nurse',
                'country'            => 'England',
                'city'               => 'Birmingham',
                'street'             => 'Bacon road 2',
                'zipCode'            => '35005',
                'bankAccountNumber'  => 'QWERTYUI2',
                'wage'               => '800',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 24,
                'name'               => 'Ali Whitehead',
                'email'              => 'aliwhitehead@gmail.com',
                'password'           => bcrypt('aliwhitehead'),
                'role'               => 'nurse',
                'country'            => 'England',
                'city'               => 'Birmingham',
                'street'             => 'Bacon road 15',
                'zipCode'            => '35005',
                'bankAccountNumber'  => 'QWERTYUI15',
                'wage'               => '800',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));

        DB::table('users')->insert(array(
            array(
                'id'                 => 25,
                'name'               => 'River Hawkins',
                'email'              => 'riverhawkins@gmail.com',
                'password'           => bcrypt('riverhawkins'),
                'role'               => 'nurse',
                'country'            => 'England',
                'city'               => 'Birmingham',
                'street'             => 'Bacon road 17',
                'zipCode'            => '35005',
                'bankAccountNumber'  => 'QWERTYUI17',
                'wage'               => '820',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 26,
                'name'               => 'Erin Graham',
                'email'              => 'eringraham@gmail.com',
                'password'           => bcrypt('eringraham'),
                'role'               => 'nurse',
                'country'            => 'England',
                'city'               => 'Birmingham',
                'street'             => 'Bacon road 18',
                'zipCode'            => '35005',
                'bankAccountNumber'  => 'QWERTYUI18',
                'wage'               => '830',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 27,
                'name'               => 'Lane Woods',
                'email'              => 'lanewoods@gmail.com',
                'password'           => bcrypt('lanewoods'),
                'role'               => 'nurse',
                'country'            => 'England',
                'city'               => 'Birmingham',
                'street'             => 'Bacon road 18',
                'zipCode'            => '35005',
                'bankAccountNumber'  => 'QWERTYUI18',
                'wage'               => '840',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 28,
                'name'               => 'Jesse Lewis',
                'email'              => 'jesselewis@gmail.com',
                'password'           => bcrypt('jesselewis'),
                'role'               => 'nurse',
                'country'            => 'England',
                'city'               => 'Birmingham',
                'street'             => 'Bacon road 19',
                'zipCode'            => '35005',
                'bankAccountNumber'  => 'QWERTYUI19',
                'wage'               => '850',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 29,
                'name'               => 'Caden Campbell',
                'email'              => 'cadencampbell@gmail.com',
                'password'           => bcrypt('cadencampbell'),
                'role'               => 'nurse',
                'country'            => 'England',
                'city'               => 'Birmingham',
                'street'             => 'Sausage hill 936',
                'zipCode'            => '35010',
                'bankAccountNumber'  => 'PKOWTYUI963',
                'wage'               => '870',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
        DB::table('users')->insert(array(
            array(
                'id'                 => 30,
                'name'               => 'Frankie Stuart',
                'email'              => 'frankiestuart@gmail.com',
                'password'           => bcrypt('frankiestuart'),
                'role'               => 'nurse',
                'country'            => 'England',
                'city'               => 'Birmingham',
                'street'             => 'Hillton road 222',
                'zipCode'            => '35010',
                'bankAccountNumber'  => 'QWERTYUI2',
                'wage'               => '800',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));

        DB::table('users')->insert(array(
            array(
                'id'                 => 31,
                'name'               => 'Gabe Baxter',
                'email'              => 'gabebaxter@gmail.com',
                'password'           => bcrypt('gabebaxter'),
                'role'               => 'nurse',
                'country'            => 'England',
                'city'               => 'Birmingham',
                'street'             => 'Bacon road 16',
                'zipCode'            => '35005',
                'bankAccountNumber'  => 'QWERTYUI16',
                'wage'               => '810',
                'remember_token'     => NULL,
                'created_at'         => $today->format('Y-m-d H:i:s'),
                'updated_at'         => $today->format('Y-m-d H:i:s'),
                'lastLogin'          => $today->format('Y-m-d H:i:s'),
            ),
        ));
    }
}
